"""Contract tests for PROBE-A: the rig, the geometry it derives, and the judge.

Two jobs, and the second is the one that keeps the first honest:

  * **the rig's derived quantities are what they claim to be** -- the grasp frame is a
    constant of the model, the finger stroke brackets the part, the part is tall enough for
    the fingers to clear the surface, and the upstream asset is untouched;
  * **the judge can FAIL.** Every criterion is fed a synthetic input that MUST produce FAIL
    (no contact, never leaves the table, dragged along the surface, drifts after release,
    still gripped at the end, skipped a stage, and a world that welds the part to something).
    A check that cannot be shown to fail is not a check -- the C branch shipped a permanently
    false sequence check for a whole round because nothing ever tried to break it.
"""
import ast
import hashlib
import json
import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'experiments'))
import arm_rig as rig                                                  # noqa: E402

PANDA = ROOT / 'assets' / 'panda'
WORLD = rig.WORLD
JUDGE = ROOT / 'experiments' / 'evaluate_arm.py'

REST_Z = rig.payload_rest_z()
PICK = rig.PICK_XY
PLACE = rig.PLACE_XY


def _model_and_data():
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    return model, data, mujoco


def _grasp_pose_achieved():
    """Put the arm at the grasp pose and return (model, data, achieved point, lowest z)."""
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    plan = mujoco.MjData(model)
    b = rig.ids(model)
    mujoco.mj_resetData(model, data)
    data.qpos[b['arm_qadr']] = model.key_qpos[0][:7]
    data.qpos[b['finger_qadr']] = model.key_qpos[0][7:9]
    data.ctrl[:] = model.key_ctrl[0]
    mujoco.mj_forward(model, data)
    for _ in range(1000):
        mujoco.mj_step(model, data)
    rot = rig.home_hand_rot(model, plan)
    target = (PICK[0], PICK[1], REST_Z)
    plan.qpos[:] = data.qpos
    q, _, _ = rig.ik(model, plan, target, target_rot=rot,
                     q_seed=list(data.qpos[b['arm_qadr']]))
    data.ctrl[b['arm_dof']] = q
    for _ in range(600):
        mujoco.mj_step(model, data)
    return model, data, rig.grasp_point(model, data), rig.gripper_min_world_z(model, data)


# =======================================================================================
# the rig
# =======================================================================================

def test_the_generated_world_matches_its_source():
    """`--check` must agree, or the committed scene has drifted from arm_rig's constants."""
    assert rig.build(check=True) == 0


def test_the_upstream_model_is_read_not_written():
    """The panda.xml in the project must still be the file that was downloaded.

    The world is generated FROM this file, so if it were ever edited in place the generated
    scene would stop being traceable to a published revision.
    """
    import json as _json
    manifest = _json.loads((ROOT / 'assets' / 'manifest-panda.json').read_text())
    on_disk = hashlib.sha256(rig.PANDA_XML.read_bytes()).hexdigest()
    assert on_disk == manifest['sha256']['assets/panda/panda.xml'], (
        'assets/panda/panda.xml no longer matches the recorded upstream revision')


def test_every_panda_asset_file_matches_the_manifest():
    import json as _json
    manifest = _json.loads((ROOT / 'assets' / 'manifest-panda.json').read_text())
    missing, wrong = [], []
    for rel, want in manifest['sha256'].items():
        p = ROOT / rel
        if not p.is_file():
            missing.append(rel)
        elif hashlib.sha256(p.read_bytes()).hexdigest() != want:
            wrong.append(rel)
    assert not missing, f'assets listed in the manifest are missing: {missing}'
    assert not wrong, f'assets have changed since they were recorded: {wrong}'


def test_the_world_differs_from_upstream_only_by_the_two_documented_substitutions():
    """Nothing inside the upstream body tree may be edited."""
    upstream = rig.PANDA_XML.read_text(encoding='utf-8')
    world = WORLD.read_text(encoding='utf-8')
    # the generated block is delimited, so it can be removed mechanically
    start = world.index('\n    <!-- ===== generated by experiments/arm_rig.py')
    end = world.index('</worldbody>')
    stripped = world[:start] + world[end:]
    stripped = stripped.replace(f'meshdir="{rig.PANDA_MESH_SUBDIR}"',
                                f'meshdir="{rig.UPSTREAM_MESHDIR}"')
    stripped = stripped.replace(f'model="{rig.MODEL_NAME}"', 'model="panda"')
    assert stripped == upstream, (
        'the generated world is not the upstream model plus the documented substitutions')


def test_the_grasp_frame_is_a_constant_of_the_model_not_a_typed_number():
    """Derived, and independent of the pose it is measured in."""
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    b = rig.ids(model)
    seen = []
    for seed in (model.key_qpos[0][:7], list(model.key_qpos[0][:7] + 0.3)):
        data.qpos[b['arm_qadr']] = seed
        mujoco.mj_forward(model, data)
        seen.append(rig.grasp_local_offset(model, data))
    assert max(abs(a - c) for a, c in zip(seen[0], seen[1])) < 1e-12, (
        'the grasp offset must not depend on the pose')
    # and it must equal the pad-centre midpoint recomputed from world geometry
    hand = b['hand']
    R = data.xmat[hand].reshape(3, 3)
    p = data.xpos[hand]
    centres = [data.geom_xpos[rig._pad_geom(model, s)]
               for s in ('left_finger', 'right_finger')]
    expect = R.T @ ((centres[0] + centres[1]) / 2.0 - p)
    assert max(abs(a - c) for a, c in zip(seen[0], expect)) < 1e-12
    assert seen[0][0] == pytest.approx(0.0, abs=1e-9) and \
        seen[0][1] == pytest.approx(0.0, abs=1e-9), (
            'the grasp frame must sit on the closing axis, i.e. its x and y are zero')


def test_the_finger_gap_brackets_the_part():
    """Open must clear the part, closed must press it. Measured, not assumed."""
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    b = rig.ids(model)
    grip = model.actuator(rig.GRIPPER_ACTUATOR).id
    gaps = {}
    for ctrl in (0.0, 255.0):
        mujoco.mj_resetData(model, data)
        data.qpos[b['arm_qadr']] = model.key_qpos[0][:7]
        data.qpos[b['finger_qadr']] = model.key_qpos[0][7:9]
        data.ctrl[:] = model.key_ctrl[0]
        data.ctrl[grip] = ctrl
        mujoco.mj_forward(model, data)
        for _ in range(6000):
            mujoco.mj_step(model, data)
        gaps[ctrl] = rig.finger_gap(model, data)
    width = 2.0 * rig.PAYLOAD_HALF[0]
    assert gaps[0.0] < width < gaps[255.0], (
        f'closed gap {gaps[0.0]:.4f} must be under the part width {width:.4f}, and open '
        f'{gaps[255.0]:.4f} must be over it')


def test_the_part_is_tall_enough_for_the_fingers_to_clear_the_surface():
    """The derived constraint that the first part did NOT satisfy.

    The fingers reach 21.6 mm below the grasp frame. A grasp centred on a short part drives
    the fingertip into the work surface, and the friction there stops the gripper closing --
    at mu=1.0 that made the grip FAIL while mu=0.6 passed, which is a physically correct but
    very confusing result, and it wasted a whole round.
    """
    model, data, achieved, lowest = _grasp_pose_achieved()
    reach = achieved[2] - lowest
    need = rig.TABLE_TOP_Z + reach
    assert REST_Z >= need - 1e-9, (
        f'the grasp frame sits at {REST_Z:.4f} but the fingers reach {reach * 1000:.2f} mm '
        f'below it, so they only clear the surface above {need:.4f}')


def test_the_gripper_does_not_touch_the_table_at_the_grasp_pose():
    model, data, achieved, lowest = _grasp_pose_achieved()
    contacts = rig.contacts_between(model, data, rig.ids(model)['gripper_bodies'],
                                    rig.ids(model)['table'])
    assert lowest > rig.TABLE_TOP_Z, (
        f'the lowest gripper vertex is at {lowest:.4f}, below the table top '
        f'{rig.TABLE_TOP_Z:.4f}')
    assert not contacts, f'the gripper is already touching the table: {contacts}'


def test_the_payload_is_a_free_body_and_no_equality_references_it():
    """The anti-fake-attach condition, checked at model level."""
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    b = rig.ids(model)
    assert any(model.jnt_type[j] == mujoco.mjtJoint.mjJNT_FREE
               and int(model.jnt_bodyid[j]) == b['payload'] for j in range(model.njnt)), \
        'the payload must be a free body'
    for e in range(model.neq):
        ids = {int(model.eq_obj1id[e]), int(model.eq_obj2id[e])}
        assert b['payload'] not in ids and b['payload_joint'] not in ids, (
            f'equality {e} references the payload: a planned attach must not be able to '
            f'stand in for contact')
    # and the gripper's own coupling must still be there, so the check above is not vacuous
    assert model.neq >= 1, (
        'the upstream gripper couples its two finger joints; if that equality is gone this '
        'test is no longer demonstrating anything about scoping')


def test_the_arm_never_moves_the_payload_by_anything_but_contact():
    """A source-level guarantee, in two halves.

    The arm's OWN joints are initialised from the home keyframe -- that is setup, and
    TEST_AND_ACCEPTANCE permits ground truth for initialisation. What must never happen is the
    PAYLOAD's state being written: a teleport, or a keyframe reset that lands on the free
    joint. The second one actually happened here (`mj_resetDataKeyframe` pads a 9-value
    keyframe out to nq=16, and the padding hit the payload), so it is worth a standing guard.
    """
    src = (ROOT / 'experiments' / 'probe_arm.py').read_text(encoding='utf-8')
    tree = ast.parse(src)
    # Comments and docstrings are not AST nodes, so the explanation of this very bug does not
    # trip the guard -- a plain substring search did.
    calls = [ast.unparse(n) for n in ast.walk(tree)
             if isinstance(n, ast.Call)
             and getattr(getattr(n, 'func', None), 'attr', None) == 'mj_resetDataKeyframe']
    assert not calls, (
        f'the probe calls {calls}: in a merged model a keyframe reset can write the payload '
        f'free joint, which moves the part without contact')
    marker = 'while data.time < SIM_SECONDS_MAX:'
    loop_line = src[:src.index(marker)].count(chr(10)) + 1
    offenders = []
    for n in ast.walk(tree):
        if not isinstance(n, ast.Assign):
            continue
        for t in n.targets:
            if isinstance(t, ast.Subscript) and 'qpos' in ast.unparse(t.value) \
                    and 'payload' in ast.unparse(t.slice) and n.lineno >= loop_line:
                offenders.append(f'line {n.lineno}: {ast.unparse(n)}')
    assert not offenders, (
        f'the probe assigns to the payload qpos INSIDE the control loop: {offenders}. '
        f'Ground truth may place the part before the run -- TEST_AND_ACCEPTANCE permits that '
        f'-- but once the machine is running, only contact may move it.')


def test_ik_converges_to_every_planned_pose_and_refuses_the_impossible():
    import mujoco
    model, data = rig.load(rig.DEFAULT_FRICTION)
    b = rig.ids(model)
    q = list(model.key_qpos[0][:7])
    worst = 0.0
    for name, target in rig.planned_poses().items():
        q, pe, re = rig.ik(model, data, target, q_seed=q)
        worst = max(worst, pe, re)
    assert worst < 1e-3, f'worst IK residual {worst:.2e}'
    with pytest.raises(RuntimeError):
        rig.ik(model, data, (3.0, 3.0, 3.0), q_seed=q)


# =======================================================================================
# the judge -- and the inputs that must break it
# =======================================================================================

def _rec(state, t, payload, grasp, grip=(), tbl=4, speed=0.0, palm=0):
    return {'t': t, 'state': state, 'payload': list(payload), 'grasp': list(grasp),
            'payload_quat': [1.0, 0.0, 0.0, 0.0], 'payload_speed': speed,
            'arm_q': [0.0] * 7, 'finger_q': [0.02, 0.02], 'gap': 0.033,
            'grip_ctrl': 0.0, 'grip_contacts': sorted(grip), 'palm_contact_n': palm,
            'table_contact_n': tbl, 'floor_contact_n': 0, 'finger_table_contact_n': 0}


def healthy_records(n_hold=100, offset=(0.0, 0.0)):
    """A trace the judge should call PASS: picked up, carried, placed, released, steady.

    `offset` displaces the part, mirroring a run whose declared start is the pick target plus
    a perturbation. The judge cross-checks the declared start against `pick_xy + part_offset`,
    so a fixture that ignored the offset would be testing a different report shape.
    """
    dx, dy = offset
    recs, t = [], 0.0

    def run(state, count, payload, grasp, grip=(), tbl=4, speed=0.0):
        nonlocal t
        for _ in range(count):
            t += 0.02
            recs.append(_rec(state, t, payload, grasp, grip, tbl, speed))

    lifted = (PICK[0] + dx, PICK[1] + dy, REST_Z + rig.LIFT_HEIGHT)
    carried = (PLACE[0] + dx, PLACE[1] + dy, REST_Z + rig.LIFT_HEIGHT)
    placed = (PLACE[0] + dx, PLACE[1] + dy, REST_Z)
    ground = (PICK[0] + dx, PICK[1] + dy, REST_Z)
    run('APPROACH', 60, ground, (PICK[0] + dx, PICK[1] + dy, REST_Z + 0.10), ())
    run('DESCEND', 40, ground, (PICK[0] + dx, PICK[1] + dy, REST_Z), ())
    run('CLOSE', 60, ground, (PICK[0] + dx, PICK[1] + dy, REST_Z),
        ('left_finger', 'right_finger'))
    run('LIFT', 80, lifted, lifted, ('left_finger', 'right_finger'), tbl=0)
    run('CARRY', 90, carried, carried, ('left_finger', 'right_finger'), tbl=0)
    run('LOWER', 80, placed, placed, ('left_finger', 'right_finger'), tbl=4)
    run('RELEASE', 30, placed, placed, ('right_finger',), tbl=4)
    run('RETREAT', 100, placed, (PLACE[0] + dx, PLACE[1] + dy, REST_Z + rig.RETREAT_HEIGHT),
        (), tbl=4)
    run('HOLD', n_hold, placed, (PLACE[0] + dx, PLACE[1] + dy, REST_Z + rig.RETREAT_HEIGHT),
        (), tbl=4)
    return recs


def synth(tmp_path, name, runs, *, records=None, world_text=None, stages=None,
          claim='CLAIMED', requires=None):
    """Write a report + traces the judge can read, mirroring the probe's real shape."""
    run_dir = tmp_path / name
    run_dir.mkdir(parents=True, exist_ok=True)
    if world_text is None:
        world = WORLD
    else:
        world = tmp_path / f'{name}_world.xml'
        world.write_text(world_text, encoding='utf-8')
    entries = []
    for i, r in enumerate(runs):
        entry = {
            'scenario': {'name': r.get('scenario_name', 'nominal'),
                         'expect': r.get('expect', 'DONE'),
                         'in_envelope': r.get('in_envelope', True)},
            'friction': r.get('friction', 0.6),
            'final_state': r.get('final_state', 'DONE'),
            'faulted': r.get('faulted', False),
            'fell_at': r.get('fell_at'),
            # the declared start is the pick target PLUS the perturbation -- the judge
            # cross-checks exactly that, so a fixture that ignored the offset would look like
            # a run whose part was not where it said it was
            'part_offset': list(r.get('part_offset', [0.0, 0.0])),
            'initial_payload': r.get('initial_payload',
                                     [PICK[0] + r.get('part_offset', [0.0, 0.0])[0],
                                      PICK[1] + r.get('part_offset', [0.0, 0.0])[1],
                                      REST_Z]),
            'transitions': r.get('transitions',
                                 [{'state': s, 't': 0.1 * k}
                                  for k, s in enumerate(rig.COORDINATE_PATH)]),
            'stages_executed': r.get('stages_executed', list(rig.COORDINATE_PATH)),
            'payload_contact_samples': r.get('payload_contact_samples', 300),
            'sim_seconds': r.get('sim_seconds', 18.0),
            'trace_file': f'trace_{i}.json',
        }
        entries.append(entry)
        if records is not None:
            payload_records = records(r) if callable(records) else records
            (run_dir / f'trace_{i}.json').write_text(
                json.dumps({'records': payload_records}), encoding='utf-8')
    report = {
        'run_id': name,
        'world': str(world),
        'world_sha256': hashlib.sha256(world.read_bytes()).hexdigest(),
        'table_top_z': rig.TABLE_TOP_Z,
        'payload_half': list(rig.PAYLOAD_HALF),
        'payload_mass': rig.PAYLOAD_MASS,
        'pick_xy': list(PICK),
        'place_xy': list(PLACE),
        'requires': list(requires if requires is not None else rig.COORDINATE_PATH),
        'stages_in_source': list(stages if stages is not None
                                 else rig.COORDINATE_PATH),
        'full_A_acceptance': claim,
        'scope_claim': 'A FIXED-ARM COMPONENT; stand-in work surface.',
        'runs': entries,
        'thresholds': {
            'min_contact_samples': rig.MIN_CONTACT_SAMPLES,
            'lift_margin_m': rig.LIFT_MARGIN,
            'carried_slip_max_m': rig.CARRIED_SLIP_MAX,
            'place_tol_xy_m': rig.PLACE_TOL_XY,
            'release_drift_max_m': rig.RELEASE_DRIFT_MAX,
            'release_speed_max_mps': rig.RELEASE_SPEED_MAX,
            'touchdown_tol_m': rig.TOUCHDOWN_TOL,
        },
    }
    (run_dir / 'report.json').write_text(json.dumps(report), encoding='utf-8')
    return tmp_path


def judge(tmp_path, name, runs, **kw):
    reports = synth(tmp_path, name, runs, **kw)
    done = subprocess.run([sys.executable, str(JUDGE), '--run-id', name,
                           '--reports-dir', str(reports)],
                          capture_output=True, text=True)
    acceptance = reports / name / 'acceptance.json'
    assert acceptance.is_file(), (
        f'the judge wrote no acceptance.json (rc={done.returncode}); '
        f'stderr: {done.stderr[-2000:]}')
    return done.returncode, json.loads(acceptance.read_text())


def verdicts(payload):
    return {c['check']: c['verdict'] for c in payload['checks']}


MUST_FAIL = {'scenario_name': 'grip_never_closes', 'expect': 'GRIP_FAILED',
             'final_state': 'GRIP_FAILED', 'faulted': True}


OFFSETS = [{'part_offset': [0.0, 0.005]}, {'part_offset': [0.005, 0.0]},
           {'part_offset': [0.004, -0.006]}]


def test_a_healthy_run_passes_every_check(tmp_path):
    # The arm carries a declared failure on purpose. Without it the judge reports the
    # falsifiability check as NOT_RUN, and the artifact is INCOMPLETE rather than PASS --
    # which is the correct behaviour and is asserted separately below. It also carries three
    # distinct part placements, because one pose repeated is not repeatability.
    # OUTSIDE is required too: without a run beyond the declared envelope the judge
    # reports that check as NOT_RUN -- correct, because a boundary nothing is run
    # against is an assumption -- and the artifact comes out INCOMPLETE, not PASS.
    OUTSIDE = {'scenario_name': 'part_shift_x_p5', 'in_envelope': False}
    rc, payload = judge(tmp_path, 'a_healthy',
                        [{}] + OFFSETS + [dict(MUST_FAIL), OUTSIDE],
                        records=lambda r: healthy_records(
                            offset=tuple(r.get('part_offset', (0.0, 0.0)))))
    assert payload['verdict'] == 'PASS', json.dumps(verdicts(payload), indent=1)
    assert rc == 0


def test_an_arm_with_no_declared_failure_is_incomplete_not_pass(tmp_path):
    """Falsifiability: an all-green judge that has never been shown a failure is INCOMPLETE."""
    rc, payload = judge(tmp_path, 'a_no_bad_case', [{}], records=healthy_records())
    assert verdicts(payload)['a case that must fail does fail'] == 'NOT_RUN'
    assert payload['verdict'] == 'INCOMPLETE'


def test_the_fixture_is_actually_reaching_the_judge(tmp_path):
    """If the fixture silently failed to load, every must-FAIL test below would pass."""
    rc, payload = judge(tmp_path, 'a_reach', [{}], records=healthy_records())
    names = {c['check'] for c in payload['checks']}
    assert 'the gripper really touches the payload' in names
    assert verdicts(payload)['the gripper really touches the payload'] == 'PASS'
    rc, payload = judge(tmp_path, 'a_reach2', [{}], records=[])
    assert verdicts(payload)['the gripper really touches the payload'] == 'FAIL', (
        'with no records at all the contact check must FAIL, not silently pass')


def test_missing_traces_are_not_run_rather_than_passed(tmp_path):
    rc, payload = judge(tmp_path, 'a_missing', [{}], records=None)
    v = verdicts(payload)
    assert v['the gripper really touches the payload'] == 'NOT_RUN'
    assert payload['verdict'] == 'INCOMPLETE'


def test_a_run_that_never_touches_the_part_fails(tmp_path):
    recs = [_rec(r['state'], r['t'], r['payload'], r['grasp'], (), r['table_contact_n'])
            for r in healthy_records()]
    _, payload = judge(tmp_path, 'a_nocontact', [{}], records=recs)
    v = verdicts(payload)
    assert v['the gripper really touches the payload'] == 'FAIL'
    assert v['the payload leaves the table'] == 'FAIL'


def test_a_run_that_lifts_the_part_by_a_hair_fails(tmp_path):
    recs = healthy_records()
    for r in recs:
        if r['payload'][2] > REST_Z:
            r['payload'] = [r['payload'][0], r['payload'][1],
                            REST_Z + rig.LIFT_MARGIN / 2.0]
    _, payload = judge(tmp_path, 'a_shortlift', [{}], records=recs)
    assert verdicts(payload)['the payload leaves the table'] == 'FAIL'


def test_a_run_that_drags_the_part_along_the_surface_fails(tmp_path):
    """Lifted height reached, but still touching the table: that is sliding, not lifting."""
    recs = healthy_records()
    for r in recs:
        if r['payload'][2] > REST_Z + rig.LIFT_MARGIN / 2.0 and r['state'] in ('LIFT', 'CARRY'):
            r['table_contact_n'] = 2
    _, payload = judge(tmp_path, 'a_drag', [{}], records=recs)
    assert verdicts(payload)['the payload leaves the table'] == 'FAIL'


def test_a_run_that_leaves_the_part_behind_fails(tmp_path):
    """The part rises with the arm but slips out of the hand as it goes."""
    recs = healthy_records()
    for i, r in enumerate(recs):
        if r['state'] in ('LIFT', 'CARRY') and r['grip_contacts']:
            r['payload'] = [r['payload'][0] + 0.01 * i, r['payload'][1], r['payload'][2]]
    _, payload = judge(tmp_path, 'a_slip', [{}], records=recs)
    assert verdicts(payload)['the payload is carried, not left behind'] == 'FAIL'


def test_a_run_that_puts_the_part_in_the_wrong_place_fails(tmp_path):
    recs = healthy_records()
    for r in recs:
        if r['state'] in ('RELEASE', 'RETREAT', 'HOLD'):
            r['payload'] = [r['payload'][0] + 0.20, r['payload'][1], r['payload'][2]]
    _, payload = judge(tmp_path, 'a_place', [{}], records=recs)
    assert verdicts(payload)['the payload is placed at the declared target'] == 'FAIL'


def test_a_run_that_still_holds_the_part_at_the_end_fails(tmp_path):
    recs = healthy_records()
    for r in recs:
        if r['state'] == 'HOLD':
            r['grip_contacts'] = ['left_finger', 'right_finger']
    _, payload = judge(tmp_path, 'a_held', [{}], records=recs)
    assert verdicts(payload)['the payload is released and stays put'] == 'FAIL'


def test_a_part_that_drifts_after_release_fails(tmp_path):
    recs = healthy_records()
    n = 0
    for r in recs:
        if r['state'] == 'HOLD':
            n += 1
            r['payload'] = [r['payload'][0] + 0.001 * n, r['payload'][1], r['payload'][2]]
            r['payload_speed'] = 0.5
    _, payload = judge(tmp_path, 'a_drift', [{}], records=recs)
    v = verdicts(payload)
    assert v['the payload is released and stays put'] == 'FAIL'


def test_a_sequence_that_skips_a_stage_fails(tmp_path):
    order = [s for s in rig.COORDINATE_PATH if s != 'LIFT']
    runs = [{'transitions': [{'state': s, 't': 0.1 * k} for k, s in enumerate(order)],
             'stages_executed': order}]
    _, payload = judge(tmp_path, 'a_skip', runs, records=healthy_records())
    assert verdicts(payload)['the sequence ran in order and to the end'] == 'FAIL'


def test_a_sequence_out_of_order_fails(tmp_path):
    order = list(rig.COORDINATE_PATH)
    order[3], order[4] = order[4], order[3]
    runs = [{'transitions': [{'state': s, 't': 0.1 * k} for k, s in enumerate(order)],
             'stages_executed': order}]
    _, payload = judge(tmp_path, 'a_order', runs, records=healthy_records())
    assert verdicts(payload)['the sequence ran in order and to the end'] == 'FAIL'


def test_a_run_that_drops_its_part_fails(tmp_path):
    _, payload = judge(tmp_path, 'a_drop', [{'fell_at': 12.5}], records=healthy_records())
    assert verdicts(payload)['no run loses the payload it is carrying'] == 'FAIL'


def test_a_case_that_should_fail_but_succeeds_is_reported(tmp_path):
    runs = [{'scenario_name': 'grip_never_closes', 'expect': 'GRIP_FAILED',
             'final_state': 'DONE'}]
    _, payload = judge(tmp_path, 'a_notfail', runs, records=healthy_records())
    assert verdicts(payload)['a case that must fail does fail'] == 'FAIL'


def test_a_world_that_welds_the_part_is_a_failure(tmp_path):
    """The anti-fake-attach check, exercised: an equality on the payload must be caught.

    meshdir is rewritten to an absolute path so the synthetic world can live outside assets/
    and still compile -- the same trap that made the generated world unusable from the report
    directory.
    """
    mesh = (ROOT / 'assets' / rig.PANDA_MESH_SUBDIR).resolve()
    text = WORLD.read_text(encoding='utf-8')
    text = text.replace(f'meshdir="{rig.PANDA_MESH_SUBDIR}"', f'meshdir="{mesh}"')
    assert '<equality>' in text
    text = text.replace('<equality>',
                        '<equality>\n    <weld body1="payload" body2="table" solref="0.02 1"/>')
    _, payload = judge(tmp_path, 'a_weld', [{}], records=healthy_records(),
                       world_text=text)
    v = verdicts(payload)
    assert v['nothing attaches the payload to the gripper'] == 'FAIL'


def test_a_world_that_changed_after_the_run_is_a_failure(tmp_path):
    """Evidence about a different machine is not evidence."""
    reports = synth(tmp_path, 'a_stale', [{}], records=healthy_records())
    report = json.loads((reports / 'a_stale' / 'report.json').read_text())
    report['world_sha256'] = '0' * 64
    (reports / 'a_stale' / 'report.json').write_text(json.dumps(report))
    done = subprocess.run([sys.executable, str(JUDGE), '--run-id', 'a_stale',
                           '--reports-dir', str(reports)], capture_output=True, text=True)
    payload = json.loads((reports / 'a_stale' / 'acceptance.json').read_text())
    assert verdicts(payload)['nothing attaches the payload to the gripper'] == 'FAIL'
    assert done.returncode == 1


def test_a_stale_claim_disagreeing_with_the_stage_list_fails(tmp_path):
    runs = [{'stages_executed': list(rig.COORDINATE_PATH)}]
    short = [s for s in rig.COORDINATE_PATH if s != 'LIFT']
    _, payload = judge(tmp_path, 'a_claim', runs, records=healthy_records(),
                       stages=short, claim='CLAIMED')
    v = verdicts(payload)
    assert v['the whole-A claim is not made without its stages'] == 'FAIL'


def test_the_scope_sentence_is_derived_in_both_directions(tmp_path):
    """With nothing missing the sentence must not still say A is undecidable, and vice versa."""
    runs = [{'stages_executed': list(rig.COORDINATE_PATH)}]
    _, payload = judge(tmp_path, 'a_scope_all', runs, records=healthy_records())
    detail = next(c['detail'] for c in payload['checks']
                  if c['check'] == 'the whole-A claim is not made without its stages')
    assert 'Whether A as a whole passes cannot be decided' not in detail
    assert 'declared scope' in detail

    short = [s for s in rig.COORDINATE_PATH if s != 'LIFT']
    _, payload = judge(tmp_path, 'a_scope_missing', [{}], records=healthy_records(),
                       stages=short, claim='NOT_RUN')
    detail = next(c['detail'] for c in payload['checks']
                  if c['check'] == 'the whole-A claim is not made without its stages')
    assert 'Whether A as a whole passes cannot be decided' in detail
