"""The generated charge-run id must be unique across task-service generations.

`request_id` is the ledger's idempotency key, the ledger is durable on purpose, and
`charge_serial` restarts at 1 in every process. So the first charge run of a new session
reused the id of a dead one, `Ledger.submit` -- correctly -- reported `created=False`,
and the caller returned early **after** the charge pad had been granted. The pad was then
held for the rest of the session by a robot with no task to release it, and the status
page showed a plausible occupant.
"""

from __future__ import annotations

import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src"
for _pkg in ("fleet_core", "fleet_adapter"):
    _p = SRC / _pkg
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from fleet_core import Ledger, charge_request_id  # noqa: E402


def test_the_id_is_stable_for_the_same_generation():
    assert charge_request_id("r01", 7, 1) == charge_request_id("r01", 7, 1)


def test_a_new_generation_cannot_collide_with_a_dead_one():
    first = charge_request_id("r01", 111, 1)
    second = charge_request_id("r01", 222, 1)
    assert first != second, (
        "a charge run generated by a new task service shares an id with one generated by "
        "a previous one, and the durable ledger will refuse to create it"
    )


def test_it_is_readable_because_it_ends_up_in_the_event_log():
    rid = charge_request_id("r03", 42, 7)
    assert rid.startswith("auto-charge-r03-")
    assert "42" in rid and rid.endswith("-7")


def test_the_collision_this_prevents_is_real_at_the_ledger(tmp_path):
    """The mechanism, demonstrated through the ledger rather than asserted about strings.

    Submitting the OLD scheme's id twice is exactly what happened: the second submit
    returns `created=False` and the caller has nothing to attach the granted pad to.
    """
    led = Ledger(tmp_path / "fleet.sqlite")
    from fleet_core import TaskKind, TaskSpec

    old_scheme = "auto-charge-r01-1"          # no epoch: what the code used to generate
    spec = TaskSpec(request_id=old_scheme, pick_station="S_left_a", drop_station="C_left",
                    kind=TaskKind.RETURN_TO_CHARGE)
    _task, created_first = led.submit(spec, now=0.0, epoch=1, task_id=old_scheme)
    _task2, created_again = led.submit(spec, now=1.0, epoch=2, task_id=old_scheme)
    assert created_first is True
    assert created_again is False, (
        "the old id scheme is not unique across generations, which is the defect"
    )

    # and with the epoch in the id, the same second attempt does create a task
    new_scheme = charge_request_id("r01", 2, 1)
    spec2 = TaskSpec(request_id=new_scheme, pick_station="S_left_a", drop_station="C_left",
                     kind=TaskKind.RETURN_TO_CHARGE)
    _task3, created_new = led.submit(spec2, now=2.0, epoch=2, task_id=new_scheme)
    assert created_new is True
