- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
- ros_topic_name: /odom
  gz_topic_name: /mm/odom
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
- ros_topic_name: /scan_raw
  gz_topic_name: /mm/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
- ros_topic_name: /cmd_vel
  gz_topic_name: /mm/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ
- ros_topic_name: /joint_states
  gz_topic_name: /mm/joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /camera/image_raw
  gz_topic_name: /mm/camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /camera/camera_info
  gz_topic_name: /mm/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /mm/physics
  gz_topic_name: /mm/physics
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /mm/grasp_command
  gz_topic_name: /mm/grasp_command
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/shoulder
  gz_topic_name: /mm/joint/shoulder
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/elbow
  gz_topic_name: /mm/joint/elbow
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/lift
  gz_topic_name: /mm/joint/lift
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/wrist
  gz_topic_name: /mm/joint/wrist
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/finger_left
  gz_topic_name: /mm/joint/finger_left
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /mm/joint/finger_right
  gz_topic_name: /mm/joint/finger_right
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
