#!/usr/bin/env python3
"""Fail the build when AMCL's update step is larger than the gate's escape hatch.

WHY THIS EXISTS
---------------
Two numbers in two files, owned by two different subsystems, and they must satisfy one
inequality. When they do not, the gate is guaranteed to refuse motion -- not occasionally,
on every update interval.

    AMCL `update_min_d`        how far the robot must move before the localiser publishes a
                               new `amcl_pose`. Measured for the stock value 0.25 m.

    the gate's `max_moved_m`   how far the robot may move since the estimate arrived and
                               still be considered bounded by it (`localiser_move_margin_m`).

If `update_min_d` > `max_moved_m`, then between two estimates the robot crosses the hatch and
the gate stops publishing `cmd_vel`. The only way back is the reactive no-motion refresh, so
the loop is: drive a little, get refused, wait for a refresh, drive a little. Measured
2026-09-18, N05 (batch_20260918T061032Z), stock 0.25 against a 0.10 hatch:

    case        no-motion refreshes   refusals   Nav2 aborts (error 105)
    passed                    220        256        0
    failed                    395        227       17
    failed                    405        262       18

and Nav2's controller has `SimpleProgressChecker` at `required_movement_radius: 0.5` /
`movement_time_allowance: 10.0`, so a stall caused by the refusal becomes
`Failed to make progress`, the behaviour server clears both costmaps and replans, and a 68 s
approach becomes a 194 s one.

NOTHING EXISTED THAT COULD CATCH IT
    * both files are valid, both numbers are deliberate-looking, and each is documented
      locally as if it were the only one;
    * `docs/LIMITATIONS.md` said the AMCL update rule was "load-bearing for the gate's
      liveness" -- which is a sentence, not a check;
    * the unit tests build `LocaliserPolicy(max_moved_m=0.10)` by hand and so never see the
      value the ROS nodes actually use;
    * the generators assert the value they write, so a regeneration happily rewrites the
      other side.

So: read both numbers from where they are really kept, and assert the inequality.

WHAT THIS DOES NOT COVER -- READ THIS BEFORE TREATING A GREEN RUN AS "THE POSE IS SAFE"
    `LocaliserPolicy` calls a pose usable when EITHER of two conditions holds:

        age   <= max_age_s     (`localiser_timeout_s`, 2.0 s)     <-- NOT checked here
        moved <= max_moved_m   (`localiser_move_margin_m`, 0.100 m) <-- this file

    This file asserts the SECOND one. Nothing here says anything about the first, and a
    green result below has been read as if it did. The age condition is the one that fires
    in practice: the gate logs `localised pose is 2.011 s old (> 2.00 s) and the robot has
    moved 0.124 m since it arrived`, which is the AGE clause, 83 times in N07. The bound is
    checked against the recordings by `scripts/check_localiser_age.py`, which re-derives it
    from the measured age distribution instead of quoting the comment that justifies it.

The two ends live here:
    AMCL  -- src/fleet_bringup/config/nav2_params.yaml (GENERATED by gen_nav2_params.py;
             edit the generator, never this file)
    hatch -- the declared default of `localiser_move_margin_m` in the ROS nodes, because no
             YAML overrides it. If one ever does, this guard says so rather than guessing.

Exit 0 when the inequality holds, 1 when it does not, 3 on an environment problem.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARAMS = ROOT / "src" / "fleet_bringup" / "config" / "nav2_params.yaml"
NODES = [
    ROOT / "src" / "fleet_ros" / "fleet_ros" / "gate_node.py",
    ROOT / "src" / "fleet_ros" / "fleet_ros" / "coordinator_node.py",
]
HATCH_KEY = "localiser_move_margin_m"
#: Any YAML the nodes could be given at launch that would override the declared default.
OVERRIDE_YAMLS = [ROOT / "config" / "fleet.yaml", ROOT / "config" / "resources.yaml"]


def _amcl_rule() -> tuple[float, float] | None:
    """`(update_min_d, update_min_a)` from the generated Nav2 parameters."""
    try:
        import yaml
    except ImportError:
        print("check_pose_freshness.py: PyYAML is missing from this interpreter",
              file=sys.stderr)
        return None
    if not PARAMS.is_file():
        print(f"check_pose_freshness.py: {PARAMS.relative_to(ROOT)} is missing", file=sys.stderr)
        return None
    body = yaml.safe_load(PARAMS.read_text(encoding="utf-8")) or {}
    amcl = (body.get("amcl") or {}).get("ros__parameters") or {}
    if "update_min_d" not in amcl:
        print("check_pose_freshness.py: the amcl block has no update_min_d", file=sys.stderr)
        return None
    return float(amcl["update_min_d"]), float(amcl.get("update_min_a", -1.0))


def _hatch() -> dict[str, float] | None:
    """Every declared default for the hatch, keyed by the file that declares it."""
    found: dict[str, float] = {}
    for node in NODES:
        if not node.is_file():
            print(f"check_pose_freshness.py: {node.relative_to(ROOT)} is missing",
                  file=sys.stderr)
            return None
        tree = ast.parse(node.read_text(encoding="utf-8"), filename=str(node))
        for call in ast.walk(tree):
            if not isinstance(call, ast.Call):
                continue
            func = call.func
            if not (isinstance(func, ast.Attribute) and func.attr == "declare_parameter"):
                continue
            if len(call.args) < 2:
                continue
            name, default = call.args[0], call.args[1]
            if not (isinstance(name, ast.Constant) and name.value == HATCH_KEY):
                continue
            if not isinstance(default, ast.Constant) or not isinstance(default.value, (int, float)):
                continue
            found[str(node.relative_to(ROOT))] = float(default.value)
    return found or None


def _overrides() -> list[str]:
    """Any YAML in the tree that sets the hatch, which would make the default a decoy."""
    hits: list[str] = []
    for path in OVERRIDE_YAMLS:
        if path.is_file() and HATCH_KEY in path.read_text(encoding="utf-8"):
            hits.append(str(path.relative_to(ROOT)))
    return hits


def main() -> int:
    if not PARAMS.is_file():
        print("check_pose_freshness.py: run me from the repository root", file=sys.stderr)
        return 3

    rule = _amcl_rule()
    hatch = _hatch()
    if rule is None or hatch is None:
        return 3
    update_min_d, update_min_a = rule

    print(f"  AMCL update_min_d = {update_min_d:.3f} m, update_min_a = {update_min_a:.3f} rad"
          f"   ({PARAMS.relative_to(ROOT)})")

    overrides = _overrides()
    if overrides:
        print(f"  [skip] {HATCH_KEY} is also set in: {', '.join(overrides)}; this guard reads "
              "only the declared default and cannot say which one wins")
        return 0

    values = set(hatch.values())
    for where, value in sorted(hatch.items()):
        print(f"  gate hatch max_moved_m = {value:.3f} m   (declared in {where})")
    if len(values) != 1:
        print(f"  [FAIL] the nodes disagree about the hatch: {sorted(values)}. The gate and "
              "the coordinator must make the same decision about the same subject.")
        return 1

    max_moved = values.pop()
    print()
    if update_min_d > max_moved:
        print(f"  [FAIL] update_min_d ({update_min_d:.3f}) > max_moved_m ({max_moved:.3f}).")
        print(f"         The robot crosses the hatch before a new estimate arrives, so the gate")
        print(f"         refuses partway through EVERY update interval and only a no-motion")
        print(f"         refresh clears it. Measured at these values: 227-262 refusals per run")
        print(f"         and 17-18 Nav2 `Failed to make progress` aborts, against 0 on a run")
        print(f"         that happened to keep up.")
        print(f"         Either lower `update_min_d` in scripts/gen_nav2_params.py and")
        print(f"         regenerate, or raise `{HATCH_KEY}` in the nodes -- and if the")
        print(f"         hatch moves, re-derive it: see docs/DECISIONS.md D-P15-02.")
        return 1
    if update_min_d <= 0.0:
        print(f"  [FAIL] update_min_d is {update_min_d}; a non-positive bound updates on every "
              "odometry sample, which is not what anyone meant by '0'.")
        return 1

    print(f"  OK: update_min_d ({update_min_d:.3f}) <= max_moved_m ({max_moved:.3f}); the robot "
          "can complete one full update interval without the hatch closing")
    print("  Note: this covers the DISTANCE condition only. The AGE condition "
          "(max_age_s / localiser_timeout_s) is checked against the recordings by "
          "scripts/check_localiser_age.py, which re-derives the bound rather than "
          "trusting its comment.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
