#!/usr/bin/env python3
"""Render assets/models/amr_4wd/model.sdf.in into one model directory per robot.

Why render instead of shipping two SDFs by hand: the topic and TF frame names must
be unique per robot, and everything else must be identical. A template makes that
a mechanical substitution, so the two robots cannot drift apart in wheelbase or
mass, and a reviewer can see that the ONLY difference is __ROBOT__.

What it guarantees, and checks rather than assumes:

  * Every __ROBOT__ occurrence is replaced. If any survives, this fails loudly: a
    leftover token becomes a literal topic name called "__ROBOT__" that silently
    never receives anything.
  * The rendered SDF contains no double hyphen inside an XML comment. libsdformat
    tolerates that, but strict parsers reject the file outright, so it is a real
    portability defect, not a style choice.
  * The rendered file parses as XML.

Usage:
    scripts/render_model.py --robot r01 [--robot r02] [--out runtime/models]
    scripts/render_model.py --robot r01 --print-topics
"""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "assets" / "models" / "amr_4wd" / "model.sdf.in"
TOKEN = "__ROBOT__"

# Robot names go into topic names, frame ids and directory names, so restrict them
# to something that cannot inject separators or escape the output directory.
ROBOT_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,15}$")

MODEL_CONFIG = """<?xml version="1.0" ?>
<!-- Generated by scripts/render_model.py from assets/models/amr_4wd/model.sdf.in.
     Do not edit: edit the template and re-render. -->
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.10">model.sdf</sdf>
  <author>
    <name>ziling</name>
    <email>ziling@zephastra.local</email>
  </author>
  <description>
    009 four-wheel skid-steer AMR, rendered for robot {name}. Topics and frames are
    absolute and carry the {name} prefix.
  </description>
</model>
"""


class RenderError(RuntimeError):
    pass


def check_no_double_hyphen_in_comments(text: str) -> list[str]:
    problems: list[str] = []
    for match in re.finditer(r"<!--(.*?)-->", text, re.DOTALL):
        body = match.group(1)
        if "--" in body:
            line = text[: match.start()].count("\n") + 1
            problems.append(f"line {line}: '--' inside an XML comment")
    return problems


def render(robot: str, template_text: str) -> str:
    if not ROBOT_RE.match(robot):
        raise RenderError(
            f"invalid robot name {robot!r}: must match {ROBOT_RE.pattern} "
            "(it becomes a topic name and a frame id, so it must not contain "
            "separators)"
        )
    out = template_text.replace(TOKEN, robot)
    if TOKEN in out:
        raise RenderError(
            f"placeholder {TOKEN} survived rendering for {robot}: the substitution "
            "is incomplete and the model would carry a literal topic named "
            f"{TOKEN}"
        )
    return out


def verify(robot: str, text: str) -> None:
    bad = check_no_double_hyphen_in_comments(text)
    if bad:
        raise RenderError(f"{robot}: XML comment defect: " + "; ".join(bad))
    try:
        ET.fromstring(text)
    except ET.ParseError as exc:  # pragma: no cover - reported, not raised
        raise RenderError(f"{robot}: rendered SDF is not well formed XML: {exc}") from exc


def topics_for(robot: str) -> dict[str, str]:
    return {
        "/" + robot + "/cmd_vel": "GZ IN   (bridged from ROS)  gz.msgs.Twist",
        "/" + robot + "/odom": "GZ OUT  (bridged to ROS)    gz.msgs.Odometry",
        "/" + robot + "/tf": "GZ OUT  (bridged to ROS /tf) gz.msgs.Pose_V",
        "/" + robot + "/joint_states": "GZ OUT  (bridged to ROS)    gz.msgs.Model",
        "/" + robot + "/scan": "GZ OUT  (bridged to ROS)    gz.msgs.LaserScan",
        # Truth is NOT a per-robot topic. Two per-model attempts produced either a
        # silent dead topic (gz published gz.msgs.Pose, the bridge wanted Pose_V) or no
        # publisher at all. What works is the world-level dynamic_pose/info, bridged as
        # Pose_V -> TFMessage, which delivers the model pose without its name or stamp.
        "world dynamic_pose/info": "GZ OUT (evaluator only)  gz.msgs.Pose_V",
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--robot", action="append", required=True,
                    help="robot name, e.g. r01 (repeat for several)")
    ap.add_argument("--out", default=str(ROOT / "runtime" / "models"),
                    help="output directory (default runtime/models)")
    ap.add_argument("--print-topics", action="store_true",
                    help="print the absolute topic names each robot will use")
    args = ap.parse_args(argv)

    if not TEMPLATE.is_file():
        print(f"FATAL: template not found: {TEMPLATE}", file=sys.stderr)
        return 2
    template_text = TEMPLATE.read_text(encoding="utf-8")
    if TOKEN not in template_text:
        print(f"FATAL: template contains no {TOKEN}: nothing would be substituted, "
              "which means every robot would share one topic set", file=sys.stderr)
        return 2

    out_root = Path(args.out)
    # De-duplicate but keep order so repeated --robot values are harmless.
    seen: list[str] = []
    for r in args.robot:
        if r not in seen:
            seen.append(r)

    try:
        for robot in seen:
            text = render(robot, template_text)
            verify(robot, text)
            target = out_root / f"amr_4wd_{robot}"
            target.mkdir(parents=True, exist_ok=True)
            (target / "model.sdf").write_text(text, encoding="utf-8")
            (target / "model.config").write_text(
                MODEL_CONFIG.format(name=robot), encoding="utf-8")
            print(f"[ OK ] rendered {robot} -> {target}")
    except RenderError as exc:
        print(f"FATAL: {exc}", file=sys.stderr)
        return 1

    if args.print_topics:
        print()
        for robot in seen:
            print(f"=== {robot} ===")
            for topic, note in topics_for(robot).items():
                print(f"  {topic:36} {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
